### PR TITLE
Changing screenshot for vcs deployment as per CP-6091

### PR DESCRIPTION
**Pull request by Mona2012**

### CODE REVIEW

**Comment by Mona2012** [comment]
Changed the screenshot in Step 6: Deploy HDM to the Cloud under 2.2 HDM Documentation -> VCS: IBM Cloud for VMware Solutions Dedicated -> Deployment Steps as follows -

image1

**Review by ayyajpio — APPROVED** [review]
Looks good to me.

**Review by kgcb — COMMENTED** [review]
Shouldn't the image be for IBM VCS instead of VMC?

**Review by kgcb — APPROVED** [review]
Looks good to me.

**Pull request merged**
